
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label lblEarthWeight;

	private global::Gtk.Label lblMarsWeight;

	private global::Gtk.Entry eWeightField;

	private global::Gtk.Button btnConvert;

	private global::Gtk.Entry mWeightField;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Your Weight on Mars");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblEarthWeight = new global::Gtk.Label();
		this.lblEarthWeight.Name = "lblEarthWeight";
		this.lblEarthWeight.LabelProp = global::Mono.Unix.Catalog.GetString("Enter your weight on Earth");
		this.fixed1.Add(this.lblEarthWeight);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblEarthWeight]));
		w1.X = 49;
		w1.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblMarsWeight = new global::Gtk.Label();
		this.lblMarsWeight.Name = "lblMarsWeight";
		this.lblMarsWeight.LabelProp = global::Mono.Unix.Catalog.GetString("Your Weight on Mars");
		this.fixed1.Add(this.lblMarsWeight);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblMarsWeight]));
		w2.X = 79;
		w2.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.eWeightField = new global::Gtk.Entry();
		this.eWeightField.CanFocus = true;
		this.eWeightField.Name = "eWeightField";
		this.eWeightField.Text = global::Mono.Unix.Catalog.GetString("100");
		this.eWeightField.IsEditable = true;
		this.eWeightField.InvisibleChar = '●';
		this.fixed1.Add(this.eWeightField);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.eWeightField]));
		w3.X = 227;
		w3.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnConvert = new global::Gtk.Button();
		this.btnConvert.CanFocus = true;
		this.btnConvert.Name = "btnConvert";
		this.btnConvert.UseUnderline = true;
		this.btnConvert.Label = global::Mono.Unix.Catalog.GetString("Convert");
		this.fixed1.Add(this.btnConvert);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnConvert]));
		w4.X = 251;
		w4.Y = 213;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.mWeightField = new global::Gtk.Entry();
		this.mWeightField.CanFocus = true;
		this.mWeightField.Name = "mWeightField";
		this.mWeightField.IsEditable = false;
		this.mWeightField.InvisibleChar = '●';
		this.fixed1.Add(this.mWeightField);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.mWeightField]));
		w5.X = 226;
		w5.Y = 134;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 516;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnConvert.Clicked += new global::System.EventHandler(this.ButtonConvert_Clicked);
	}
}
